version: "3.1"
services:
  mongodb:
    image: mongo:4.4.1
    restart: unless-stopped
    ports:
      - 27017:27017

  mongodb-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  server:
    build: ./server
    restart: unless-stopped
    volumes:
      - ./config/server.production.env:/usr/src/app/.env
    depends_on: 
      - mongodb

  graphql:
    build: ./graphql-api
    ports:
      - 4000:4000
    volumes:
      - ./config/graphql.production.env:/usr/src/app/.env
    depends_on: 
      - server

  client:
    build: ./client
    ports:
      - 9000:80
    depends_on: 
      - graphql