version: "3.1"
services:
  mongo:
    image: mongo:4.4.1
    restart: unless-stopped
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
